# extract.FeatureExtractor.extract { #pyseter.extract.FeatureExtractor.extract }

```python
extract.FeatureExtractor.extract(image_dir, bbox_csv=None)
```

Extracts features from images.

Extracts feature vectors for every image in a directory with the 
AnyDorsal algorithm.  

## Parameters {.doc-section .doc-section-parameters}

| Name      | Type   | Description                                                                                                                               | Default    |
|-----------|--------|-------------------------------------------------------------------------------------------------------------------------------------------|------------|
| image_dir | str    | Directory of images to from which to extract features. Directory  should be flat, in that there should not be subdirectories with images. | _required_ |
| bbox_csv  | str    | Optional path to csv file with bounding boxes for each image in the  image_dir.                                                           | `None`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                                                                                                                                                                                                                                               |
|--------|--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | dict   | A mapping image file names to the corresponding feature vector.  The file names are represented as strings, while the feature vector. is a NumPy array. For example: ``` {'img1.jpg': np.array([0.1, 0.1, 0.2, ..., 0.9]),  'img2.jpg': np.array([0.2, 0.3, 0.4, ..., 0.1])} ``` The numpy array should have length 5504. |

## Raises {.doc-section .doc-section-raises}

| Name   | Type             | Description                                                                                                             |
|--------|------------------|-------------------------------------------------------------------------------------------------------------------------|
|        | OutOfMemoryError | The GPU has run out of memory. Try reducing your batch size, or  reducing the file size of the images in the directory. |