# API Reference {.doc .doc-index}

## Feature Extraction

Extracting feature vectors from images

| | |
| --- | --- |
| [extract.FeatureExtractor](extract.FeatureExtractor.qmd#pyseter.extract.FeatureExtractor) | Extract features from images. |

## Identify

Predicting IDs in a query set with a reference set

| | |
| --- | --- |
| [identify.predict_ids](identify.predict_ids.qmd#pyseter.identify.predict_ids) | Predict the identities of individuals in the query set |

## Sorting and Clustering

Clustering images by proposed IDs

| | |
| --- | --- |
| [sort.HierarchicalCluster](sort.HierarchicalCluster.qmd#pyseter.sort.HierarchicalCluster) | Hierarchical clustering of images |
| [sort.NetworkCluster](sort.NetworkCluster.qmd#pyseter.sort.NetworkCluster) | Network clustering of images |
| [sort.ClusterResults](sort.ClusterResults.qmd#pyseter.sort.ClusterResults) | Storing NetworkCluster results. |
| [sort.prep_images](sort.prep_images.qmd#pyseter.sort.prep_images) | Copy all images to a flat directory and save a csv with encounter info. |
| [sort.sort_images](sort.sort_images.qmd#pyseter.sort.sort_images) | Sort images into subfolders by proposed ID then encounter. |
| [sort.load_features](sort.load_features.qmd#pyseter.sort.load_features) | Load previously extracted features. |

## Grading

Grade images by distinctiveness

| | |
| --- | --- |
| [grade.rate_distinctiveness](grade.rate_distinctiveness.qmd#pyseter.grade.rate_distinctiveness) | Grade images by their distinctiveness. |

## Verifying Installation

Functions to make sure PyTorch is working

| | |
| --- | --- |
| [get_best_device](get_best_device.qmd#pyseter.get_best_device) | Select torch device based on expected performance. |
| [verify_pytorch](verify_pytorch.qmd#pyseter.verify_pytorch) | Verify PyTorch installation and show device options. |